dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1
  - jruby-9.2
deploy:
  provider: rubygems
  api_key:
    secure: qt98vo9xoyZJ25/SOIHiTyHIEuIkPN7lvE7mrCUfLcn1eWovg/7vFcK4I7/w+0xbrpyy1a7Ivmez9mV6ePH9VX/NrTQAw2tAoG3VgHPp4Oh0iiV9xL/nZSDTaF6nTLXySqR8mtGFWEmNmgUyQ5ID0lznFhfwHVWxF8vJNR0lg65JtjfLuOLDhZEhOGRaRUJjgjRB0gT9qusDwr+0cUQKbt+pNLkAdvS8srBnKkM1n7xnU1KSt4M6gyAi1ODc6MN8Q0QMLZw8356HoEVYgSNUm6iLAIeSdqAXv2Gl6X5qwVURvkfPcMadhipwP9o86kesEafw0eFbvHuYn9ZfxItCm+wrkXogB5iVY4Uk41DVtCi6f0zzYq3j5YwvO4srdjtNgaqQl9HY/05e64JzR++PH0qy3Xoq/FVRcNqa6fmNxnx6AmxAJ5kKDalhA4JlUtsyIoJ3kqHbY3OVNfgjZXfEmajJmt2QzYqf0nA11NqZEP0z/VxNx2xgaqiU2HVc/LK8Er3xzrYWEQd0xLnv4j45QnjGxt1z87/aMRCcqA7VRJ1roDIolY8MGNLAjwslxM7+qMHGpnTQvVmMNVPDpWEJtb8wl21ap8byy7zg9lzbyWkVuVjKhT6ZfZAB73y5G9tq8OywKgnM2j7HrL3Gh2uQ3n/Kuxh2Cq4CfyKClZt2b/o=
  gem: moceansdk
  on:
    tags: true
    ruby: 2.6
  skip_cleanup: true